[tool.poetry]
name = "aoc_2018"
version = "0.1.0"
description = ""
authors = ["Jared Priddle <jared@sindarin.org>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
